// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Real values live in .env.local (Neon CLI writes them there), not .env.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations/introspection use Neon's unpooled connection -- Neon's pooler
  // is PgBouncer transaction-mode, which doesn't support the session-level
  // features (advisory locks, prepared statements) Prisma's migration engine
  // needs. The app's runtime PrismaClient uses the pooled DATABASE_URL
  // instead (see src/lib/prisma.ts).
  datasource: {
    url: process.env["DATABASE_URL_UNPOOLED"],
  },
});
